"""Multi-strategy fuzzy find-and-replace for the ``edit`` tool.

Patches generated by an LLM rarely agree with the on-disk file byte-for-
byte: whitespace collapses, smart quotes sneak in via paste, indentation
shifts when the model "remembers" the file from earlier context, and
tool-call JSON serialisation occasionally injects backslash-escapes
around apostrophes / double quotes.

This module ships a chain of progressively more permissive matchers.
The first one that hits is used; we ALSO refuse a match when the input
looks like it was corrupted in transit (escape-drift detection) — that's
better than silently writing ``\\'`` literals into source code.

Strategies (priority order):
    1. exact                 — bytes identical
    2. line_trimmed          — strip per-line whitespace
    3. whitespace_normalized — collapse runs of spaces / tabs to one
    4. indentation_flexible  — drop all leading whitespace
    5. escape_normalized     — translate ``\\n``/``\\t``/``\\r`` literals
    6. unicode_normalized    — smart quotes, em/en-dash, NBSP, ellipsis
    7. block_anchor          — first+last 2 lines match
    8. context_aware         — difflib similarity ≥ 0.92
"""

from __future__ import annotations

import re
from difflib import SequenceMatcher

UNICODE_MAP = {
    "“": '"',
    "”": '"',
    "‘": "'",
    "’": "'",
    "—": "--",
    "–": "-",
    "…": "...",
    " ": " ",
}


class FuzzyMatchError(Exception):
    """Raised when no strategy could safely place the patch."""

    def __init__(self, message: str, *, strategies_tried: list[str], near_miss: str = "") -> None:
        super().__init__(message)
        self.strategies_tried = strategies_tried
        self.near_miss = near_miss


def _unicode_normalize(text: str) -> str:
    out = text
    for src, dst in UNICODE_MAP.items():
        out = out.replace(src, dst)
    return out


# ── Strategies (each returns (new_content, count) on success or None) ─


def _exact(content: str, old: str, new: str) -> tuple[str, int] | None:
    if old not in content:
        return None
    count = content.count(old)
    return content.replace(old, new), count


def _line_trimmed(content: str, old: str, new: str) -> tuple[str, int] | None:
    old_lines = [l.rstrip().lstrip() for l in old.split("\n")]
    pat = "\n".join(old_lines)
    content_lines = content.split("\n")
    norm_lines = [l.rstrip().lstrip() for l in content_lines]
    n = len(old_lines)
    if n == 0 or n > len(norm_lines):
        return None
    matches: list[tuple[int, int]] = []
    for i in range(len(norm_lines) - n + 1):
        block = "\n".join(norm_lines[i : i + n])
        if block == pat:
            matches.append((i, i + n))
    if not matches:
        return None
    return _splice_lines(content, content_lines, matches, new), len(matches)


def _whitespace_normalized(content: str, old: str, new: str) -> tuple[str, int] | None:
    def norm(s: str) -> str:
        return re.sub(r"[ \t]+", " ", s)

    old_n = norm(old)
    norm_content_full = norm(content)
    # Only kick in when normalisation actually changes something — otherwise
    # we'd be duplicating the exact-match strategy.
    if old_n == old and norm_content_full == content:
        return None
    if old_n not in norm_content_full:
        return None
    content_lines = content.split("\n")
    norm_lines = [norm(l) for l in content_lines]
    pat_lines = old_n.split("\n")
    n = len(pat_lines)
    if n == 0 or n > len(norm_lines):
        return None
    matches: list[tuple[int, int]] = []
    for i in range(len(norm_lines) - n + 1):
        block = "\n".join(norm_lines[i : i + n])
        if block == old_n:
            matches.append((i, i + n))
    if not matches:
        return None
    return _splice_lines(content, content_lines, matches, new), len(matches)


def _indentation_flexible(content: str, old: str, new: str) -> tuple[str, int] | None:
    old_lines = [l.lstrip() for l in old.split("\n")]
    pat = "\n".join(old_lines)
    content_lines = content.split("\n")
    norm_lines = [l.lstrip() for l in content_lines]
    n = len(old_lines)
    if n == 0 or n > len(norm_lines):
        return None
    matches: list[tuple[int, int]] = []
    for i in range(len(norm_lines) - n + 1):
        block = "\n".join(norm_lines[i : i + n])
        if block == pat:
            matches.append((i, i + n))
    if not matches:
        return None
    return _splice_lines(content, content_lines, matches, new), len(matches)


def _escape_normalized(content: str, old: str, new: str) -> tuple[str, int] | None:
    def unescape(s: str) -> str:
        return s.replace("\\n", "\n").replace("\\t", "\t").replace("\\r", "\r")

    old_u = unescape(old)
    if old_u == old:
        return None
    if old_u not in content:
        return None
    count = content.count(old_u)
    return content.replace(old_u, new), count


def _unicode_normalized(content: str, old: str, new: str) -> tuple[str, int] | None:
    norm_content = _unicode_normalize(content)
    norm_old = _unicode_normalize(old)
    if norm_content == content and norm_old == old:
        return None
    # Line-aligned search on normalized data, splice on original lines
    # using positional index (lines align 1:1 because UNICODE_MAP only
    # changes characters within a line, never adds/removes line breaks).
    content_lines = content.split("\n")
    norm_lines = norm_content.split("\n")
    pat_lines = norm_old.split("\n")
    n = len(pat_lines)
    if n == 0 or n > len(norm_lines):
        return None
    matches: list[tuple[int, int]] = []
    for i in range(len(norm_lines) - n + 1):
        block = "\n".join(norm_lines[i : i + n])
        if block == norm_old:
            matches.append((i, i + n))
    if not matches:
        return None
    return _splice_lines(content, content_lines, matches, new), len(matches)


def _block_anchor(content: str, old: str, new: str) -> tuple[str, int] | None:
    old_lines = old.split("\n")
    if len(old_lines) < 4:
        return None  # need first+last 2 lines for a meaningful anchor
    head = [l.strip() for l in old_lines[:2]]
    tail = [l.strip() for l in old_lines[-2:]]
    content_lines = content.split("\n")
    n = len(old_lines)
    if n > len(content_lines):
        return None
    matches: list[tuple[int, int]] = []
    for i in range(len(content_lines) - n + 1):
        block = content_lines[i : i + n]
        if (
            block[0].strip() == head[0]
            and block[1].strip() == head[1]
            and block[-2].strip() == tail[0]
            and block[-1].strip() == tail[1]
        ):
            matches.append((i, i + n))
    if not matches:
        return None
    return _splice_lines(content, content_lines, matches, new), len(matches)


def _context_aware(content: str, old: str, new: str) -> tuple[str, int] | None:
    old_lines = old.split("\n")
    n = len(old_lines)
    content_lines = content.split("\n")
    if n == 0 or n > len(content_lines):
        return None
    best_score = 0.0
    matches: list[tuple[int, int]] = []
    for i in range(len(content_lines) - n + 1):
        block = "\n".join(content_lines[i : i + n])
        score = SequenceMatcher(None, block, old).ratio()
        if score >= 0.92:
            matches.append((i, i + n))
        if score > best_score:
            best_score = score
    if not matches:
        return None
    return _splice_lines(content, content_lines, matches, new), len(matches)


# ── helper: splice a list of (start_line, end_line) ranges with `new` ─


def _splice_lines(
    original: str,
    content_lines: list[str],
    matches: list[tuple[int, int]],
    new: str,
) -> str:
    """Reassemble ``content_lines`` after replacing each match range with ``new``.

    ``matches`` are line-index ranges (start inclusive, end exclusive).
    Sort descending so earlier indices stay valid as we splice from the
    bottom up. The original line-break style (``\\n`` vs ``\\r\\n``) is
    preserved if the original used ``\\r\\n`` exclusively.
    """
    # Detect newline style by sniffing the original.
    nl = "\r\n" if ("\r\n" in original and "\n" in original) else "\n"
    # Operate on the (already \n-split) lines, then rejoin.
    result_lines = list(content_lines)
    for start, end in sorted(matches, key=lambda m: m[0], reverse=True):
        new_lines = new.split("\n")
        result_lines[start:end] = new_lines
    return nl.join(result_lines) if nl == "\r\n" else "\n".join(result_lines)


def detect_escape_drift(content: str, old_str: str) -> bool:
    """Return True when ``old_str`` carries literal ``\\'`` / ``\\"`` not in ``content``.

    The classic JSON-tool-call serialisation bug: the model typed a
    plain ``'`` or ``"`` and the transport added a stray backslash. If
    we accepted ``old_str`` verbatim and rebuilt the file, we'd write
    those backslashes into source code. Refuse instead — the caller can
    re-emit without the spurious escapes.
    """
    for suspect in ("\\'", '\\"'):
        if suspect in old_str and suspect not in content:
            return True
    return False


# ── Public entry point ────────────────────────────────────────────────

_STRATEGIES: list[tuple[str, callable]] = [
    ("exact", _exact),
    ("line_trimmed", _line_trimmed),
    ("whitespace_normalized", _whitespace_normalized),
    ("indentation_flexible", _indentation_flexible),
    ("escape_normalized", _escape_normalized),
    ("unicode_normalized", _unicode_normalized),
    ("block_anchor", _block_anchor),
    ("context_aware", _context_aware),
]


def fuzzy_find_and_replace(
    content: str,
    old_str: str,
    new_str: str,
    *,
    expected_count: int = 1,
) -> tuple[str, str]:
    """Find ``old_str`` in ``content`` and substitute ``new_str``.

    Args:
        content:        The file contents.
        old_str:        Text the LLM thinks exists in the file.
        new_str:        Replacement text.
        expected_count: How many occurrences the caller expected. The
                        first strategy that finds at least one match is
                        used; if its count != ``expected_count`` we
                        raise ``FuzzyMatchError``.

    Returns:
        ``(new_content, strategy_used)`` on success.

    Raises:
        FuzzyMatchError: if no strategy matched, or the matched count
            disagrees with ``expected_count``, or escape-drift was
            detected.
    """
    if not old_str:
        raise FuzzyMatchError(
            "old_str must not be empty",
            strategies_tried=[],
        )
    if old_str == new_str:
        raise FuzzyMatchError(
            "old_str and new_str are identical — no-op refused",
            strategies_tried=[],
        )

    if detect_escape_drift(content, old_str):
        raise FuzzyMatchError(
            "escape-drift detected: old_str carries literal \\' or \\\" "
            "sequences absent from the file. Likely a JSON tool-call "
            "serialisation artifact — re-emit without the spurious backslash.",
            strategies_tried=["escape_drift_guard"],
        )

    tried: list[str] = []
    best_near_miss = ""
    for name, fn in _STRATEGIES:
        tried.append(name)
        result = fn(content, old_str, new_str)
        if result is None:
            continue
        new_content, count = result
        if count != expected_count:
            raise FuzzyMatchError(
                f"expected {expected_count} match(es), found {count} "
                f"(strategy {name!r}). Provide more context in old_str to "
                "disambiguate.",
                strategies_tried=tried,
                near_miss=old_str[:200],
            )
        return new_content, name

    # No strategy hit — surface the closest similarity score we saw.
    snippet = content[:200]
    if len(content) > 200:
        # Pick the highest-similarity 200-char window around old_str.
        best = 0.0
        best_idx = 0
        for i in range(0, max(1, len(content) - 200), 64):
            score = SequenceMatcher(None, content[i : i + 200], old_str).ratio()
            if score > best:
                best = score
                best_idx = i
        snippet = content[best_idx : best_idx + 200]
        best_near_miss = snippet

    raise FuzzyMatchError(
        "no strategy could place the patch",
        strategies_tried=tried,
        near_miss=best_near_miss or snippet,
    )


__all__ = [
    "FuzzyMatchError",
    "fuzzy_find_and_replace",
    "detect_escape_drift",
    "UNICODE_MAP",
]
