"""`oxenclaw setup` / `oxenclaw setup all` — one-shot full bootstrap.

Chains every first-run step so a fresh box goes from clone to a
ready-to-start gateway with a single command:

1. **System dependencies** — detect the OS / Ubuntu version and install
   the right apt packages (build toolchain, sandbox `bwrap`, the correct
   Python stack — deadsnakes on 22.04, native on 24.04+). Confirm-gated;
   prints the exact command and runs it with `sudo` on opt-in. In a
   non-interactive shell it prints the command and skips execution.
2. **Home + config** — create `~/.oxenclaw/` and scaffold a starter
   `config.yaml` when one doesn't exist yet.
3. **Gateway token** — generate + persist the bearer token so the
   dashboard login works on first start.
4. **Provider** — pick a chat backend: chain into the `llamacpp-direct`
   wizard, print the Ollama recipe, or configure a hosted provider
   (OpenAI / Gemini / Azure OpenAI) — prompting for the model + API key
   and saving the key to `~/.oxenclaw/env` (mode 0600) so the gateway
   reads it via `EnvAuthStorage` on the next start.
5. **Doctor** — run the aggregated health check and surface the verdict.

Like `LlamaCppSetupWizard`, the wizard takes an injectable `Prompter`
(stdin) and `SystemSetupIO` (filesystem / subprocess) so the whole flow
is unit-testable without touching the real machine. Every step is
re-runnable — each short-circuits when its prerequisite is already met.
"""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

from oxenclaw.flows.llamacpp_setup import Prompter
from oxenclaw.flows.system_deps import (
    PlatformInfo,
    apt_plan_for,
    detect_platform,
    non_apt_guidance,
)

_CANCEL = "leave it for now (I'll set it up myself)"

_STARTER_CONFIG = """\
# oxenclaw config — generated by `oxenclaw setup`.
# Full reference: https://github.com/andreason21/oxenClaw/tree/main/docs
#
# The bundled dashboard channel (web + native desktop) is registered
# automatically and needs no config. Slack is outbound-only — drop a
# bot token at ~/.oxenclaw/credentials/slack/main.json to wire alerts.

channels: {}

agents:
  default:
    id: default
    provider: auto          # auto | llamacpp-direct | ollama | vllm | lmstudio
                            # hosted (API key required): openai | gemini | azure-openai
    model: qwen3.5:9b
    system_prompt: |
      You are a helpful assistant.
"""


# ─── IO contract ──────────────────────────────────────────────────────


class SystemSetupIO(Protocol):
    """Side-effect surface — stubbed in tests so nothing leaves the box."""

    def emit(self, message: str) -> None: ...

    def run_command(self, argv: list[str], *, timeout: int = 1800) -> int:
        """Run a command with inherited stdio (so apt progress + the sudo
        password prompt reach the user). Returns the exit code."""
        ...


class DefaultSystemSetupIO:
    """Production IO: prints to stdout, runs apt with live passthrough."""

    def emit(self, message: str) -> None:
        print(message)

    def run_command(self, argv: list[str], *, timeout: int = 1800) -> int:
        try:
            # No capture: apt's progress bars and the interactive sudo
            # password prompt must reach the user's terminal directly.
            r = subprocess.run(argv, timeout=timeout)
        except FileNotFoundError:
            return 127
        except subprocess.TimeoutExpired:
            return 124
        return r.returncode


# ─── Result ───────────────────────────────────────────────────────────


@dataclass
class FullSetupResult:
    platform: PlatformInfo
    apt_attempted: bool = False
    apt_ok: bool | None = None
    config_path: Path | None = None
    config_created: bool = False
    token: str | None = None
    token_source: str | None = None
    provider_choice: str | None = None
    doctor_ok: bool | None = None
    notes: list[str] = field(default_factory=list)


# ─── Wizard ───────────────────────────────────────────────────────────


class FullSetupWizard:
    def __init__(
        self,
        prompter: Prompter,
        io: SystemSetupIO,
        *,
        interactive: bool = True,
        assume_yes: bool = False,
        skip_apt: bool = False,
        print_only: bool = False,
        skip_provider: bool = False,
        platform_override: PlatformInfo | None = None,
    ) -> None:
        self.prompter = prompter
        self.io = io
        # `interactive` gates whether we may run sudo apt at all. In a
        # pipe / CI shell we only print the command (the chosen default).
        self.interactive = interactive
        self.assume_yes = assume_yes
        self.skip_apt = skip_apt
        self.print_only = print_only
        self.skip_provider = skip_provider
        self._platform_override = platform_override

    # — Step 1: system dependencies ───────────────────────────────────

    def step_system_deps(self, plat: PlatformInfo) -> tuple[bool, bool | None]:
        """Install version-specific apt packages.

        Returns `(attempted, ok)` — `ok` is None when we only printed the
        command (non-interactive, declined, or `--print-only`).
        """
        if self.skip_apt:
            self.io.emit("  Skipping system dependencies (--no-apt).")
            return False, None

        if not plat.is_debian_like:
            for line in non_apt_guidance(plat):
                self.io.emit(f"  {line}")
            return False, None

        plan = apt_plan_for(plat)
        for note in plan.notes:
            self.io.emit(f"  note: {note}")

        is_root = hasattr(os, "geteuid") and os.geteuid() == 0
        sequence = plan.command_sequence(use_sudo=not is_root)

        self.io.emit("  Will run:")
        for cmd in sequence:
            self.io.emit(f"    $ {' '.join(cmd)}")

        if self.print_only or not self.interactive:
            self.io.emit(
                "  (printed only — copy the commands above, or re-run "
                "interactively / with --yes to execute them)"
            )
            return False, None

        if not self.assume_yes and not self.prompter.confirm(
            "Run these now? (sudo may prompt for your password)", default=True
        ):
            self.io.emit("  Skipped. Run the commands above yourself when ready.")
            return False, None

        for cmd in sequence:
            self.io.emit(f"  $ {' '.join(cmd)}")
            rc = self.io.run_command(cmd)
            if rc != 0:
                self.io.emit(f"  [ERR]   command failed (rc={rc}): {' '.join(cmd)}")
                self.io.emit(
                    "  Fix the error above (often a missing PPA key or no sudo "
                    "rights) and re-run `oxenclaw setup`."
                )
                return True, False
        self.io.emit("  [OK]    system dependencies installed")
        return True, True

    # — Step 2: home + config scaffold ────────────────────────────────

    def step_config(self) -> tuple[Path, bool]:
        """Ensure `~/.oxenclaw/` exists and scaffold a starter config.yaml.

        Returns `(config_path, created)` — `created` is False when a
        config was already present (left untouched).
        """
        from oxenclaw.config.paths import default_paths

        paths = default_paths()
        paths.ensure_home()
        cfg = paths.config_file
        if cfg.exists():
            self.io.emit(f"  [OK]    config exists at {cfg} (left untouched)")
            return cfg, False
        cfg.write_text(_STARTER_CONFIG, encoding="utf-8")
        self.io.emit(f"  [OK]    wrote starter config → {cfg}")
        return cfg, True

    # — Step 3: gateway token ─────────────────────────────────────────

    def step_token(self) -> tuple[str, str]:
        """Resolve / generate + persist the gateway bearer token.

        Returns `(token, source)`. The token is persisted to
        `~/.oxenclaw/gateway-token` (mode 0600) by the auth helper; the
        gateway reads it automatically on start.
        """
        from oxenclaw.config.auth_token import resolve_or_generate_token

        resolved = resolve_or_generate_token()
        if resolved.source == "generated":
            self.io.emit(f"  [OK]    generated gateway token → {resolved.path}")
        elif resolved.source == "persisted":
            self.io.emit(f"  [OK]    using persisted gateway token ({resolved.path})")
        else:
            self.io.emit(f"  [OK]    gateway token from {resolved.source} (not persisted)")
        return resolved.token, resolved.source

    # — Step 4: provider ──────────────────────────────────────────────

    def step_provider(self) -> str | None:
        """Offer to set up a chat provider. Returns the chosen provider id
        (or None when skipped)."""
        if self.skip_provider:
            self.io.emit("  Skipping provider setup (--skip-provider).")
            return None
        if not self.interactive:
            self.io.emit(
                "  Non-interactive — skipping provider setup. Run "
                "`oxenclaw setup llamacpp` or `oxenclaw setup model` later."
            )
            return None

        llamacpp = "llamacpp-direct — managed local llama.cpp (recommended, ~3x faster)"
        ollama = "ollama — classic local server (also used for embeddings)"
        hosted = "hosted — OpenAI / Gemini / Azure OpenAI (API key required)"
        choice = self.prompter.select(
            "Which chat backend would you like to set up now?",
            choices=[llamacpp, ollama, hosted, _CANCEL],
            default=llamacpp,
        )
        if choice == _CANCEL:
            self.io.emit("  Skipping provider setup; the gateway defaults to `--provider auto`.")
            return None
        if choice.startswith("llamacpp-direct"):
            return self._run_llamacpp_wizard()
        if choice.startswith("hosted"):
            return self._hosted_recipe()
        return self._ollama_recipe()

    def _run_llamacpp_wizard(self) -> str:
        from oxenclaw.flows.llamacpp_setup import (
            DefaultWizardIO,
            LlamaCppSetupWizard,
        )

        self.io.emit("")
        wizard = LlamaCppSetupWizard(prompter=self.prompter, io=DefaultWizardIO())
        wizard.run()
        return "llamacpp-direct"

    def _ollama_recipe(self) -> str:
        self.io.emit("  Ollama setup (run these in your shell):")
        self.io.emit("    curl -fsSL https://ollama.com/install.sh | sh")
        self.io.emit("    ollama pull qwen3.5:9b           # chat")
        self.io.emit("    ollama pull nomic-embed-text     # embeddings")
        self.io.emit("  Then start with: oxenclaw gateway start --provider ollama")
        return "ollama"

    def _hosted_recipe(self) -> str | None:
        """Configure an opt-in hosted provider: pick the provider, then hand
        off to the shared `configure_hosted_provider` flow (prompts for + saves
        the API key). Returns the provider id (or None when cancelled)."""
        from oxenclaw.agents.factory import CATALOG_PROVIDERS
        from oxenclaw.flows.provider_config import configure_hosted_provider
        from oxenclaw.pi.registry import is_inline_provider

        hosted = sorted(p for p in CATALOG_PROVIDERS if not is_inline_provider(p))
        if not hosted:
            self.io.emit("  No hosted providers are registered in this build.")
            return None

        provider = self.prompter.select(
            "Which hosted provider?",
            choices=[*hosted, _CANCEL],
            default=hosted[0],
        )
        if provider == _CANCEL:
            self.io.emit("  Skipping hosted provider; the gateway defaults to `--provider auto`.")
            return None

        configure_hosted_provider(provider, prompter=self.prompter, emit=self.io.emit)
        return provider

    # — Step 5: doctor ────────────────────────────────────────────────

    def step_doctor(self) -> bool:
        from oxenclaw.flows.doctor import run_doctor

        report = run_doctor(probe_embeddings=False)
        for f in report.findings:
            glyph = {"ok": "[OK]  ", "warn": "[WARN]", "error": "[ERR] "}.get(
                f.severity, f.severity
            )
            self.io.emit(f"  {glyph} {f.area}: {f.message}")
        self.io.emit(
            f"  → {len(report.errors)} error(s), {len(report.warnings)} warning(s)"
        )
        return report.ok

    # — Driver ────────────────────────────────────────────────────────

    def run(self) -> FullSetupResult:
        plat = self._platform_override or detect_platform()
        result = FullSetupResult(platform=plat)

        self.io.emit("oxenclaw setup — one-shot full bootstrap")
        self.io.emit(f"  detected: {plat.pretty}")
        if not plat.python_ok and plat.system != "Linux":
            result.notes.append(
                f"running python {'.'.join(map(str, plat.python_version))} < 3.11 — "
                "use a 3.11+ interpreter to run oxenClaw"
            )
        self.io.emit("")

        self.io.emit("Step 1/5 — system dependencies")
        result.apt_attempted, result.apt_ok = self.step_system_deps(plat)

        self.io.emit("")
        self.io.emit("Step 2/5 — home directory + config.yaml")
        result.config_path, result.config_created = self.step_config()

        self.io.emit("")
        self.io.emit("Step 3/5 — gateway token")
        result.token, result.token_source = self.step_token()

        self.io.emit("")
        self.io.emit("Step 4/5 — chat provider")
        result.provider_choice = self.step_provider()

        self.io.emit("")
        self.io.emit("Step 5/5 — doctor health check")
        result.doctor_ok = self.step_doctor()

        self.io.emit("")
        self.io.emit("Done. Next steps:")
        self.io.emit("  - oxenclaw gateway start          # boots the gateway + dashboard")
        self.io.emit("  - open http://127.0.0.1:7331/     # paste the token above to log in")
        if result.provider_choice is None:
            self.io.emit("  - oxenclaw setup llamacpp         # set up a local model when ready")
        return result


__all__ = [
    "DefaultSystemSetupIO",
    "FullSetupResult",
    "FullSetupWizard",
    "SystemSetupIO",
]
