"""Aggregated `IndexSource` — JSON catalog with TTL + stale fallback.

Reads from a configurable URL (`OXENCLAW_SKILL_INDEX_URL` env var) so
operators can publish their own pre-aggregated catalog. We don't ship
a default URL.

Catalog shape (a single JSON object):

    {
      "skills": [
        {"slug": "...", "description": "...", "tags": [...], "source": "..."},
        ...
      ]
    }
"""

from __future__ import annotations

import json
import logging
import os
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from oxenclaw.clawhub.frontmatter import SkillManifest, SkillManifestError
from oxenclaw.clawhub.sources.base import SkillBundle, SkillRef, SkillSource

logger = logging.getLogger(__name__)

INDEX_CACHE_DIR = Path.home() / ".oxenclaw" / "skills" / "index-cache"
_INDEX_TTL_SECONDS = 6 * 3600  # 6 hours
_REQUEST_TIMEOUT = 5.0


def _ensure_cache_dir() -> Path:
    INDEX_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    # Drop a `.ignore` file so ripgrep / similar tools skip the cache.
    ignore = INDEX_CACHE_DIR / ".ignore"
    if not ignore.exists():
        try:
            ignore.write_text("# generated by oxenclaw — keeps tools out\n", encoding="utf-8")
        except OSError:
            pass
    return INDEX_CACHE_DIR


def _cache_path_for(url: str) -> Path:
    safe = "".join(c if c.isalnum() else "_" for c in url)[:120]
    return _ensure_cache_dir() / f"{safe}.json"


def _read_cache(url: str) -> tuple[dict[str, Any] | None, float]:
    path = _cache_path_for(url)
    if not path.exists():
        return None, 0.0
    try:
        wrapper = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None, 0.0
    if not isinstance(wrapper, dict):
        return None, 0.0
    fetched_at = wrapper.get("_fetched_at", 0.0)
    data = wrapper.get("data")
    try:
        fa = float(fetched_at)
    except (TypeError, ValueError):
        fa = 0.0
    return data if isinstance(data, dict) else None, fa


def _write_cache(url: str, data: dict[str, Any]) -> None:
    path = _cache_path_for(url)
    try:
        wrapper = {"_fetched_at": time.time(), "data": data}
        tmp = path.with_suffix(".tmp")
        tmp.write_text(json.dumps(wrapper), encoding="utf-8")
        tmp.replace(path)
    except OSError as exc:
        logger.debug("failed to write index cache: %s", exc)


def _fetch_index(url: str) -> dict[str, Any] | None:
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "oxenclaw-skills"})
        with urllib.request.urlopen(req, timeout=_REQUEST_TIMEOUT) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError) as exc:
        logger.debug("index fetch %s failed: %s", url, exc)
        return None
    return data if isinstance(data, dict) else None


class IndexSource(SkillSource):
    """Skill source backed by a JSON catalog URL with disk-cache fallback."""

    source_id = "index"
    trust_level = "community"

    def __init__(self, url: str | None = None) -> None:
        resolved = url or os.environ.get("OXENCLAW_SKILL_INDEX_URL", "")
        self._url = (resolved or "").strip()

    @property
    def configured(self) -> bool:
        return bool(self._url)

    @property
    def fresh(self) -> bool:
        """True iff the cached index is younger than the TTL."""
        if not self._url:
            return False
        _, fa = _read_cache(self._url)
        return fa > 0 and (time.time() - fa) < _INDEX_TTL_SECONDS

    def _load(self) -> list[dict[str, Any]]:
        if not self._url:
            return []
        cached, fetched_at = _read_cache(self._url)
        if cached is not None and (time.time() - fetched_at) < _INDEX_TTL_SECONDS:
            return cached.get("skills", []) or []
        live = _fetch_index(self._url)
        if live is not None:
            _write_cache(self._url, live)
            return live.get("skills", []) or []
        # Fall back to stale cache.
        if cached is not None:
            return cached.get("skills", []) or []
        return []

    def search(self, query: str, limit: int = 10) -> list[SkillRef]:
        q = (query or "").strip().lower()
        words = q.split()
        skills = self._load()
        out: list[SkillRef] = []
        for s in skills:
            if not isinstance(s, dict):
                continue
            slug = (s.get("slug") or "").lower()
            desc = (s.get("description") or "").lower()
            combined = f"{slug} {desc}"
            if not q or q in combined or any(w in combined for w in words):
                tags_raw = s.get("tags") or []
                tags = tuple(str(t) for t in tags_raw if isinstance(t, str))
                out.append(
                    SkillRef(
                        id=str(s.get("slug") or ""),
                        slug=str(s.get("slug") or ""),
                        source_id=self.source_id,
                        description=str(s.get("description") or ""),
                        trust_level=str(s.get("trust") or self.trust_level),
                        tags=tags,
                    )
                )
            if len(out) >= limit:
                break
        return out[:limit]

    def fetch(self, skill_id: str) -> SkillBundle:
        # Index is metadata-only — full fetch must go through the source
        # the index points to. Surface what we have as a stub.
        manifest = self.inspect(skill_id)
        return SkillBundle(manifest=manifest, body="", files={})

    def inspect(self, skill_id: str) -> SkillManifest:
        for s in self._load():
            if not isinstance(s, dict):
                continue
            if s.get("slug") == skill_id:
                try:
                    return SkillManifest.model_validate(
                        {"name": skill_id, "description": s.get("description", "")}
                    )
                except Exception as exc:
                    raise SkillManifestError(str(exc)) from exc
        raise SkillManifestError(f"skill {skill_id!r} not in index")


__all__ = ["INDEX_CACHE_DIR", "IndexSource"]
